[package]
name = "rimulation"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
ndarray = "0.14.0"
ndarray-linalg = { version = "0.13", features = ["openblas-system"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
