[package]
name = "rimulation"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
approx = "0.5.1"
nalgebra = "0.33.2"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
