name = "Simulation"
uuid = "f539a35f-c2db-4586-875c-fcabf8a0e9ba"
authors = ["Fabian Weik <fabian.weik@protonmail.com>"]
version = "0.1.0"

[deps]
Serde = "db9b398d-9517-45f8-9a95-92af99003e0e"

[compat]
Serde = "3.5.0"
